#PBS -N CMAP-config-1
#PBS -j oe                   # Join error and output files for convinience
#PBS -l walltime=60:00:00    # Keep walltime big enough to finish the job
#PBS -l nodes=1:ppn=1:gpus=1 # nodes requested: Processor per node: gpus requested
#PBS -S /bin/bash            # Shell to use
#PBS -m abe                  # Mail to <user>@umich.edu on abort, begin and end
#PBS -M iljae@umich.edu      # Email id to alert
#PBS -V                      # Pass current environment variables to the script

cd /z/home/iljae/cognitive-mapping-agent
source /z/home/iljae/cognitive-mapping-agent/venv/bin/activate
python run_train_cmap.py \
	--maps=$(cat static_maps.txt) \
	--logdir=/z/home/iljae/cognitive-mapping-agent/output/config_1 \
	--random_goal=False \
	--random_spawn=False \
	--debug=True
