#PBS -N CMAP-config-5-500
#PBS -j oe                   # Join error and output files for convinience
#PBS -l walltime=60:00:00    # Keep walltime big enough to finish the job
#PBS -l nodes=1:ppn=1:gpus=1 # nodes requested: Processor per node: gpus requested
#PBS -S /bin/bash            # Shell to use
#PBS -m abe                  # Mail to <user>@umich.edu on abort, begin and end
#PBS -M iljae@umich.edu      # Email id to alert
#PBS -V                      # Pass current environment variables to the script

cd /z/home/iljae/cognitive-mapping-agent
source /z/home/iljae/cognitive-mapping-agent/venv/bin/activate
python run_train_cmap.py \
	--maps=$(cat 100_maps.txt) \
	--logdir=/z/home/iljae/cognitive-mapping-agent/output/config_5_500 \
	--num_games=20000 \
	--decay=0.999 \
	--random_goal=True \
	--random_spawn=True \
	--batch_size=4 \
	--debug=True
